# Generated by Django 4.2.4 on 2023-08-16 07:29

import django.core.validators
from django.db import migrations, models
import eventer_app.events_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(20)])),
                ('category', models.CharField(choices=[('Sports', 'Sports'), ('Festivals', 'Festivals'), ('Conferences', 'Conferences'), ('Performing Art', 'Performing Art'), ('Concerts', 'Concerts'), ('Theme Party', 'Theme Party'), ('Other', 'Other')])),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateField(validators=[eventer_app.events_app.models.validate_date_not_in_past])),
                ('event_image', models.URLField()),
            ],
        ),
    ]
