# Generated by Django 4.2.4 on 2023-08-16 07:09

import django.core.validators
from django.db import migrations, models
import eventer_app.profile_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, validators=[eventer_app.profile_app.models.validate_letters])),
                ('last_name', models.CharField(validators=[django.core.validators.MinLengthValidator(4), django.core.validators.MaxLengthValidator(30)])),
                ('email', models.EmailField(max_length=45)),
                ('profile_picture', models.URLField(blank=True, null=True)),
                ('password', models.CharField(validators=[django.core.validators.MinLengthValidator(5), django.core.validators.MaxLengthValidator(20), eventer_app.profile_app.models.validate_password])),
            ],
        ),
    ]
